name: Pulumi
on:
  push:
  workflow_dispatch:

jobs:
  PulumiPreview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Pulumi Preview
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: dev
          work-dir: ./
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_PAT }}

  PulumiDeploy:
    needs: PulumiPreview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Pulumi Deploy
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev
          work-dir: ./
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_PAT }}